### ISSUE TITLE
Hibernate version hard-coded in maven file

### ISSUE THREAD

**Issue by sptrakesh** [gt-health/GT-FHIR#108]
gt-fhir-entities/pom.xml - has hardcoded version of hibernate.

**Comment by myungchoi** [comment]
Yes. As we are moving to release 2, we are making only minimal changes we need to do. Release 2 will be developed as a separate repository.

**Comment by sptrakesh** [comment]
Is it already on GitHub?  I am trying to get this set up with MySQL/MariaDB, and did some minor changes to get the code to build using HAPI 2.4.  Would really love to look at your work in progress on 2 if possible.

**Comment by myungchoi** [comment]
No, we are working on the mapping between OMOP CDM and FHIR DM. Do you know OHDSI community? We have just created a working group to make this mapping improved. If you join this working group, you can start working on the release 2 from early stage.

**Comment by sptrakesh** [comment]
I will sign up for the OHDSI forum.  Can you share information about the working group, forum category that would be appropriate to start communications etc?
