### ISSUE TITLE
Any forum/mailing list for communication

### ISSUE THREAD

**Issue by sptrakesh** [gt-health/GT-FHIR#109]
Do you have any mailing list or forum for communication between users of the system?  I am trying to get this running using MySQL/MariaDB, and it would be great to chat with fellow users regarding setup issues, testing the system etc.

**Comment by myungchoi** [comment]
We are creating a working group within ODHSI community. Do you want that information?

**Comment by sptrakesh** [comment]
Yes, that would be great.

**Comment by myungchoi** [comment]
http://www.ohdsi.org/web/wiki/doku.php?id=projects:workgroups:fhir-wg   is the working group wiki page, which you can get information about the working group.

**Comment by sptrakesh** [comment]
Thanks
