### ISSUE TITLE
Is a starter database required with this project?

### ISSUE THREAD

**Issue by sptrakesh** [gt-health/GT-FHIR#110]
There are hard-coded id values to records in certain tables. This seems to indicate that the project assumes a starter database with certain tables populated with certain values.  Is a started database available for use with this project?

https://github.com/gt-health/GT-FHIR/blob/master/gt-fhir-entities/src/main/java/edu/gatech/i3l/fhir/dstu2/entities/PersonComplement.java - see lines 303-310.

There may be other similar instances in the code base.

**Comment by myungchoi** [comment]
There are some hard-coded concept ID. It's for FHIR to OMOP mapping. There are some required field in OMOP tables, which is not available from FHIR. In this case, we put some default value.

So, yes, you need starter database, which is OMOP v5 with Concept and Vocabulary tables are populated. These tables are read-only tables in OMOP on FHIR.

**Comment by myungchoi** [comment]
For more info on OMOP v5: http://www.ohdsi.org/web/wiki/doku.php?id=documentation:cdm:single-page

And, you can download vocabularies from https://www.ohdsi.org/data-standardization/  or http://omop.org
