### ISSUE TITLE
Are the race/ethnicity concepts for Person implemented

### ISSUE THREAD

**Issue by sptrakesh** [gt-health/GT-FHIR#111]
https://github.com/gt-health/GT-FHIR/blob/master/gt-fhir-entities/src/main/java/edu/gatech/i3l/fhir/dstu2/entities/Person.java

I see fields for race/ethnicity defined, but no code in constructEntityFromResource or getRelatedResource.  Do you have a FHIR extension for this?  Or, is this just a placeholder for future development once an extension is available?

**Comment by myungchoi** [comment]
Those are OMOP column for ethnicity. It's concept ID in OMOP schema. We had this when we defined JPA variables for each DB column, thought we will be using it. But, FHIR DSTU2 for Patient didn't have one to store this information.

**Comment by sptrakesh** [comment]
I implemented what we needed using FHIR extension.  See https://github.com/sptrakesh/GT-FHIR/commit/ecc7a2ee970319169db914bd9c7969fd347de370#diff-3e785e94afba5ceeac99967bdf9978a2 for reference if you are interested.
