### ISSUE TITLE
Missing search param MedicationPrescription and MedicationDispense

### ISSUE THREAD

**Issue by i3lgatech** [gt-health/GT-FHIR#27]
The search param **medication[x]** needs to be provided or this version. 
_Obs: This information can be retrieved from the drug concept id. Use medicationCodeableConcept to store this information._

**Comment by ismael-sarmento-jr** [comment]
@myungchoi I just checked on v0.4 pre-release and the filter medication is present. Could you be more specific on this issue?

**Comment by i3lgatech** [comment]
OK, we were looking at different version. Let's use Ballot version. Let's do this.
1. put medication. Reference string should be "Medication/<id>". 
2. Within dispense parameter in Prescription, the medication reference should also have the same format.
3. Review MedicationDispense and change the reference to include resource name.
