### ISSUE TITLE
Reference parameter

### ISSUE THREAD

**Issue by i3lgatech** [gt-health/GT-FHIR#28]
http://hl7.org/fhir/2015May/references.html

Reference parameter for internal resource should be formed as "<Resource_Name>/<id>". For example, Patient reference is "Patient/1" 

Any resources that have reference parameters need to be revisited and formatted as indicated above.

**Comment by i3lgatech** [comment]
Most reference parameters in resources have only ID number. They need to be revisited and resource name needs to be inserted.

**Comment by ismael-sarmento-jr** [comment]
The problem was confirmed for following current Resources and references:
- Observation.patient
- MedicationPrescription/Dispense.patient
- MedicationPrescription/Dispense.medication
- MedicationPrescription.encounter
