### ISSUE TITLE
Observation - 500 Internal Error

### ISSUE THREAD

**Issue by i3lgatech** [gt-health/GT-FHIR#32]
Observation is not working. Having 500 Internal Error.

**Comment by ismael-sarmento-jr** [comment]
I gathered some detailed information with @myungchoi and the following request triggers the behavior:

http://polaris.i3l.gatech.edu:8080/gt-fhir-webapp/search?serverId=home&resource=Observation&param.0.qualifier=&param.0.0=1&param.0.name=_id&param.0.type=string

The error message is "details":"Unable to find edu.gatech.i3l.fhir.dstu2.entities.VisitOccurrence with id 0"

**Comment by ismael-sarmento-jr** [comment]
Could you post on our sharepoint the backup of the database being used; I couldn't reproduce the error with the database I'm currently using.

**Comment by i3lgatech** [comment]
With a roll-back to previous DB version, this problem did not occur. The DB with a fault has been uploaded to DB storage for follow-up evaluation. I will close this.
