### ISSUE TITLE
Duplicate Resource Medication

### ISSUE THREAD

**Issue by ismael-sarmento-jr** [gt-health/GT-FHIR#41]
Distinct drug concepts should be retrieved for the resource Medication; there are duplicates when searching with no params/filters.

**Comment by ismael-sarmento-jr** [comment]
Using the query below, it's still possible to find 2304 duplicate medications in the Concept Table.
SELECT concept_name, COUNT(concept_name) FROM concept WHERE vocabulary_id = 8 GROUP BY concept_name HAVING count(concept_name) > 1 LIMIT 3000;

**Comment by i3lgatech** [comment]
They may not be a duplicates. RxNORM (or any other systems) go by the concept_code. Although their concept names are same, if they have different concept code, then it's OK. They may have different release date or one may not be unused or not valid. Something may be different. If they are truly same, but have different concept code, it's either DB mistake or RxNORM duplicates.

Just for your information...
