### ISSUE TITLE
condition search by subject is returning wrong patient condition and return only one entry.

### ISSUE THREAD

**Issue by myungchoi** [gt-health/GT-FHIR#50]
http://localhost:8080/gt-fhir-webapp/search?serverId=home&resource=Condition&param.0.0=14&param.0.name=subject&param.0.type=id&sort_by=&sort_direction=&resource-search-limit=

Subject id=14 returns a condition for patient id=9. It returns condition id=14 instead. And, patient id=14 has 30 conditions. It returns only one entry.

``` json
{
    "resourceType":"Bundle",
    "id":"e478cd3e-245c-4761-aa59-894d14240d17",
    "meta":{
        "lastUpdated":"2015-08-11T17:29:56.142-04:00"
    },
    "type":"searchset",
    "base":"http://localhost:8080/gt-fhir-webapp/base",
    "total":1,
    "link":[
        {
            "relation":"self",
            "url":"http://localhost:8080/gt-fhir-webapp/base/Condition?subject=14"
        }
    ],
    "entry":[
        {
            "resource":{
                "resourceType":"Condition",
                "id":"14",
                "patient":{
                    "reference":"Patient/9"
                },
                "code":{
                    "coding":[
                        {
                            "system":"http://snomed.info/sct",
                            "code":"46635009",
                            "display":"Type 1 diabetes mellitus"
                        }
                    ],
                    "text":"Type 1 diabetes mellitus, SNOMED-CT, 46635009"
                },
                "clinicalStatus":"unknown",
                "onsetDateTime":"1991-12-17T00:00:00-05:00",
                "notes":"Type 1 Diabetes"
            },
            "search":{
                "mode":"match"
            }
        }
    ]
}
```

**Comment by ismael-sarmento-jr** [comment]
Not confirmed. Remember you have to select the reference first, Subject in this case, and select 'subject.id', instead of writing the id right away. The id that you specified refers to Condition, instead of Patient. The correct search will generate a url like this:

http://localhost:8080/gt-fhir-webapp/search?serverId=home&resource=Condition&param.0.qualifier=&param.0.0=14&param.0.name=subject._id&param.0.type=string&sort_by=&sort_direction=&resource-search-limit=

**Comment by myungchoi** [comment]
See my comments at #48. For condition, subject only takes Patient reference. Thus, subject=[id] should be valid. To be clear, subject:Patient=[id] would be better. Either way, the search options for subject are not correct. This is valid bug.
