### ISSUE TITLE
Observation Testing Issues

### ISSUE THREAD

**Issue by charmoney** [gt-health/GT-FHIR#78]
- Anchor to existing Patient ID 33
  - Anchor to Encounter for Patient ID 33, ID 1768
  - Anchor to Condition for Patient ID 33 from Encounter 1768, ID 902
  - Anchor to Observation for Patient ID 33 from Encounter 1768, ID 7193
  - Anchor to MedicationPrescription for Patient ID 33 from Encounter 1768, ID 251
  - Anchor to Medication for Patient ID 33 from MedicationPrescription 251, ID 19049779
  - Anchor to MedicationDispense for Patient ID 33 from MedicationPrescription 251 (Medication 19049779), ID 1128
# Observation
1. CRUD READ 7193
2. Modify JSON
   - Remove ID
   - Set all timestamp years to 2015
3. CRUD Validate
   - Validation Succeeded
4. CRUD Create
   - Created ID 40475
5. CRUD Read 40475
   - **500 error: Failed to call access method**
6. Modify JSON (use 7193 JSON)
   - Set ID
   - Increment timestamp months
7. CRUD Update
   - Update OK
8. CRUD History
   - **500 error: Failed to call access method**
9. Search, _id 40475
   - **500 Internal Server Error: No message**
10. Search, Patient ID 33, Sort by _id Descending (will show new Observation)
    - **500 Internal Server Error: No message**
11. CRUD Delete
    - HTTP 204 No Content
12. CRUD Read
    - 404 not found (Better than a 500!)
13. Search, Patient ID 33, Sort by _id Descending (will show new Observation)
    - 10 records returned

**Comment by ismael-sarmento-jr** [comment]
Errors not confirmed for the newest version of the server.
