### ISSUE TITLE
Return created object on create action

### ISSUE THREAD

**Issue by natesholland** [gt-health/GT-FHIR#86]
In the create action on most of the resources, when an object is created the server returns a 201 status code (which is good) and an empty body. It would be nice if the app would render the object that was created back to the user. This would make our project for GA Tech 6440 much easier.

**Comment by charmoney** [comment]
I believe the create requests also return the ID of the new resource.  Check the HTTP headers.  I seem to recall the ID arrives in the Location header.

That said, unless returning the new resource is against the FHIR spec or REST best practices, the enhancement makes sense to me.
